### ISSUE TITLE
Support the Image Labels buildpack

### ISSUE THREAD

**Issue by ryanmoran** [paketo-community/web-servers#3]
Like all other language family buildpacks, this buildpack should include the [Image Labels buildpack](https://github.com/paketo-buildpacks/image-labels) within each of its order groups.

Addition of this buildpack should include the addition of integration tests asserting its correct functioning.

**Comment by thitch97** [comment]
Order groups:

- [x] nginx
- [x] httpd
- [ ] yarn-nginx
- [ ] npm-nginx
- [ ] yarn-httpd
- [ ] nginx-httpd
